# Import librerie e funzioni d'utilit√†

In [1]:
import os
import pandas as pd
import json
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
datasets = [
    ["00-avengers", "companiesmarketcap", "disfold", "hithorizons", "valuetoday", "jsonl", ""],
    ["01-DDD", "cbinsights", "companiesmarketcap", "ft", "teamblind", "csv", ""],
    ["02-GioPonSpiz", "disfold", "companiesmarketcap", "valuetoday", "wikipedia", "json", ""],
    ["03-gren", "companiesmarketcap", "disfold", "ft", "valuetoday", "json", ""],
    ["04-iGMM", "cbinsights", "companiesmarketcap", "disfold", "valuetoday", "json", ""],
    ["05-MalPatSaj", "companiesmarketcap", "disfold", "forbes", "wikipedia", "xlsx", ""],
    ["06-MarScoToc", "ambitiobox", "companiesmarketcap", "disfold", "wikipedia", "csv", ""],
    ["07-silvestri", "disfold", "forbes", "ft", "valuetoday", "csv", ""],
    ["08-slytherin", "disfold", "forbes", "ft", "valuetoday", "json", ""],
    ["09-wissel", "ariregister", "companiesmarketcap", "govuk", "infoclipper", "csv", "relazioni fra tabelle"],
    ["10-DeBiGa", "disfold", "globaldata", "govuk", "wikipedia", "json", ""],
    ["11-FR", "", "", "", "", "", "relazioni fra tabelle"]
]
df_datasets = pd.DataFrame(datasets, columns=["Directory", "Dataset1", "Dataset2", "Dataset3", "Dataset4", "Format", "Info"])
df_datasets

,Directory,Dataset1,Dataset2,Dataset3,Dataset4,Format,Info
0,00-avengers,companiesmarketcap,disfold,hithorizons,valuetoday,jsonl,
1,01-DDD,cbinsights,companiesmarketcap,ft,teamblind,csv,
2,02-GioPonSpiz,disfold,companiesmarketcap,valuetoday,wikipedia,json,
3,03-gren,companiesmarketcap,disfold,ft,valuetoday,json,
4,04-iGMM,cbinsights,companiesmarketcap,disfold,valuetoday,json,
5,05-MalPatSaj,companiesmarketcap,disfold,forbes,wikipedia,xlsx,
6,06-MarScoToc,ambitiobox,companiesmarketcap,disfold,wikipedia,csv,
7,07-silvestri,disfold,forbes,ft,valuetoday,csv,
8,08-slytherin,disfold,forbes,ft,valuetoday,json,
9,09-wissel,ariregister,companiesmarketcap,govuk,infoclipper,csv,relazioni fra tabelle
10,10-DeBiGa,disfold,globaldata,govuk,wikipedia,json,
11,11-FR,,,,,,relazioni fra tabelle

In [84]:
directory_datasets = "..\\datasets\\de-sources-2022-2023\\"
dataset = "datasets.json"
if os.path.isfile(dataset):
    os.remove(dataset)

In [85]:
# {group_name | dataset_name | dataset}
list_json_string = []

In [86]:
for dir_name in os.listdir(directory_datasets):
    
    tmp = os.path.join(directory_datasets, dir_name)
    directory_group = os.path.join(tmp, "datasets")

    for file_name in os.listdir(directory_group):
        
        file = os.path.join(directory_group, file_name)
        dataset_name = os.path.splitext(file_name)[0]
        file_extension = os.path.splitext(file_name)[1]
        
        if file_extension == ".jsonl":
            df = pd.read_json(file, lines=True, encoding="utf-8")
        elif file_extension == ".json":
            df = pd.read_json(file, encoding="utf-8")
        elif file_extension == ".csv":
            df = pd.read_csv(file, encoding="latin-1")
        elif file_extension == ".xlsx":
            df = pd.read_excel(file, engine='openpyxl')
        elif file_extension == ".xls":
            df = pd.read_excel(file)

        obj = {
            "group_name" : dir_name,
            "dataset_name" : dataset_name,
            "dataset" : df.to_json(orient="index")
        }
        json_object = json.dumps(obj, indent = 4) 
        list_json_string.append(json_object)

In [87]:
with open(dataset, "a") as json_file:
    json_file.write("[")
    for i in range(0, len(list_json_string) - 1):
        json_file.write(list_json_string[i])
        json_file.write(",")
    json_file.write(list_json_string[len(list_json_string) - 1])
    json_file.write("]")
    json_file.close()

In [88]:
with open(dataset, 'r', encoding='utf-8') as f:
    json_object = json.loads(f.read())
    f.close()

In [ ]:
df = pd.read_json(json_object[i]["dataset"], encoding="utf-8")